### ISSUE TITLE
Typo in Release 1.0.0

### ISSUE THREAD

**Issue by gmacario** [Three-Buddy-Problem/exoplanet-quest-web#1]
Congrats again for your achievement yesterday at the [NASA International Space Apps Challenge in Turin](https://www.spaceappschallenge.org/nasa-space-apps-2024/2024-local-events/turin/)

To prove that I read your code I found a small typo in https://github.com/Three-Buddy-Problem/exoplanet-quest-web/releases/tag/v1.0.0

Please let me know if you cannot find it 😉 

P.S.: Good luck for the global challenge!

**Comment by kaandesu** [comment]
Thank you so much for the kind words and for taking the time to check out the project! 🎉 We're really excited about the win, and your attention to detail is appreciated. I went over the release notes again and I think the typo is fixed 😊, but feel free to let us know if we missed anything! 😊

Also, fingers crossed for the global challenge—really excited about what’s next!

**Comment by gmacario** [comment]
> I went over the release notes again and I think the typo is fixed 😊, but feel free to let us know if we missed anything! 😊

Well, then I am afraid the typos were actually two 😄 

![image](https://github.com/user-attachments/assets/ab40c167-84a2-4d4d-8133-e5ea2b67ac4a)

Apart from that, Looks Really Good To Me!

Keep up the good work! -- Gianpaolo

**Comment by kaandesu** [comment]
Ohh, I see, I could never spell "challenge" correctly on first try 😄.
Again thank you so much 😄
