### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by gmacario** [Three-Buddy-Problem/exoplanet-quest-web#2]
The program is very nice and the used technology is quite interesting.

I would recommend to [place a LICENSE file](https://choosealicense.com/) to make it clear under which license the software can be reused.

If there are no preferences, I would suggest MIT

**Comment by kaandesu** [comment]
Thanks a lot for the reminder!🙏 We forgot to add it during the competition, but the MIT License is now in place.  👍

**Comment by gmacario** [comment]
> Thanks a lot for the reminder!🙏 We forgot to add it during the competition, but the MIT License is now in place. 👍

Great! Then now I feel obliged to submit a PR rather than another Issue :wink: 
https://github.com/Three-Buddy-Problem/exoplanet-quest-web/pull/3
